### ISSUE TITLE
Getting Python stacktrace after executing graphinder --help.

### ISSUE THREAD

**Issue by TMFRook** [Escape-Technologies/graphinder#49]
**Describe the bug**
Getting Python stacktrace after executing `graphinder --help`.

```
Traceback (most recent call last):
  File "/Users/paolo.delmundo/PyEnvironments/test/bin/graphinder", line 8, in <module>
    sys.exit(cli())
  File "/Users/paolo.delmundo/PyEnvironments/test/lib/python3.8/site-packages/graphinder/main.py", line 105, in cli
    main()
  File "/Users/paolo.delmundo/PyEnvironments/test/lib/python3.8/site-packages/graphinder/main.py", line 117, in main
    args: argparse.Namespace = argument_builder(argv)
  File "/Users/paolo.delmundo/PyEnvironments/test/lib/python3.8/site-packages/graphinder/main.py", line 33, in argument_builder
    action=argparse.BooleanOptionalAction,
AttributeError: module 'argparse' has no attribute 'BooleanOptionalAction'
```

**To Reproduce**
0. On Mac OS X 12.5.1, Python 3.8...
1. Install latest graphinder: `pip install graphinder`
2. Run `graphinder --help`
3. See Python stacktrace.

**Expected behavior**
This error message should not show up.

**Desktop (please complete the following information):**
 - OS: Mac OS X 12.5.1
 - Python Version: 3.8.3
 - Graphinder version 1.8.1

**Comment by c3b5aw** [comment]
Hello !

Can you try updating to 1.9.0?
